# Generated by Django 3.1 on 2020-08-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('short_desc', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Mobile Phones', 'Mobile Phones'), ('Tablets', 'Tablets'), ('Laptops', 'Laptops'), ('Headphones', 'Headphones'), ('Earbuds', 'Earbuds'), ('Camera', 'Camera')], max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('available_quantity', models.IntegerField()),
                ('image1', models.ImageField(default='default.jpg', upload_to='product_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('tags', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
