# Generated by Django 3.1 on 2020-09-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='aaa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='bbb', max_length=50),
            preserve_default=False,
        ),
    ]
