# Generated by Django 3.1 on 2020-09-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20200918_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(default=1000, max_length=10),
            preserve_default=False,
        ),
    ]
