# Generated by Django 3.1 on 2020-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_address_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
